; Quickshell LSP initialization
; See: https://quickshell.org/docs/configuration/QmllsIni

[General]
moduleImports = qs.Config
moduleImports = qs.Theme
moduleImports = qs.Bar
moduleImports = qs.Modules
moduleImports = qs.Services
moduleImports = qs.Utils
